import cymbal
import gleam/bit_array
import gleam/list
import gleam/option.{Some}
import glinfra/blueprint/app
import glinfra/blueprint/image
import glinfra/blueprint/stack.{type Stack}
import glinfra/k8s
import glinfra/k8s/deployment

const config_map_name = "sunset-relay-config"

const config_mount_path = "/etc/sunset-relay"

const config_filename = "config.toml"

/// Relay TOML config. The only setting that has to live here today is
/// `webtransport_san`: Chrome's WebTransport implementation enforces
/// SAN matching even with `serverCertificateHashes` pinning (despite
/// the W3C spec saying it shouldn't — see
/// https://github.com/w3c/webtransport/issues/623), so the relay's
/// self-signed WT cert must include the public hostname browsers dial.
/// Without this entry the cert only carries `127.0.0.1` + `localhost`
/// SANs and prod browsers fail the QUIC TLS handshake with
/// `CERTIFICATE_VERIFY_FAILED`.
const relay_config_toml = "# Generated by infra/apps/sunset_relay.gleam — do not hand-edit
# the ConfigMap; edit the Gleam source and regenerate.
listen_addr = \"0.0.0.0:8443\"
data_dir = \"/data\"
interest_filter = \"all\"
identity_secret = \"auto\"
peers = []
webtransport_san = [\"relay.sunset.chat\", \"127.0.0.1\", \"localhost\"]
"

pub fn stack() -> Stack {
  let relay_image =
    image.new("ghcr.io/nicolaschan/sunset-relay", "latest")
    |> image.with_update_pattern("^master-[0-9]+$")

  let relay_app =
    app.new("sunset-relay")
    |> app.expose_http1(8443, "relay.sunset.chat")
    |> app.expose_http1(8444, "id.relay.sunset.chat")
    |> app.add_image(relay_image)
    |> app.with_args(["--config", config_mount_path <> "/" <> config_filename])
    |> app.add_plugin(config_map_extra_resource())
    |> app.add_plugin(config_volume_mount_plugin())

  stack.new("sunset-relay")
  |> stack.add_app(relay_app)
}

/// Generate a `kind: ConfigMap` carrying the relay's TOML config under
/// the `config.toml` key. Mounted into the pod by
/// `config_volume_mount_plugin`.
fn config_map_extra_resource() -> app.AppPlugin {
  app.ExtraResources(generate: fn(ns, _application) { [config_map_yaml(ns)] })
}

fn config_map_yaml(namespace: String) -> cymbal.Yaml {
  cymbal.block([
    #("apiVersion", cymbal.string("v1")),
    #("kind", cymbal.string("ConfigMap")),
    #(
      "metadata",
      k8s.object_meta_to_cymbal(
        k8s.ObjectMeta(
          name: config_map_name,
          namespace: Some(namespace),
          labels: [],
          annotations: [],
        ),
      ),
    ),
    // Use `binaryData` (base64-encoded) instead of `data` because cymbal
    // emits multi-line strings as YAML double-quoted scalars, which
    // YAML parsers fold literal newlines into spaces — breaking the TOML
    // (which requires newlines between entries). Base64 has no
    // newlines, so cymbal's quoting can't damage it; K8s decodes
    // `binaryData` when mounting as a file, so the relay sees the
    // original TOML bytes.
    #(
      "binaryData",
      cymbal.block([
        #(
          config_filename,
          cymbal.string(bit_array.base64_encode(
            bit_array.from_string(relay_config_toml),
            True,
          )),
        ),
      ]),
    ),
  ])
}

/// Add a `ConfigMapVolume` and matching `VolumeMount` to every
/// container in the relay deployment. Combined with the `--config`
/// arg above, this makes the relay binary load the generated TOML on
/// startup instead of falling through to `Config::defaults()`.
fn config_volume_mount_plugin() -> app.AppPlugin {
  app.DeploymentPlugin(modify: fn(_application, dep) {
    let spec = dep.spec
    let template = spec.template

    let volume = deployment.ConfigMapVolume("config-volume", config_map_name)

    let mount =
      deployment.VolumeMount(
        name: "config-volume",
        mount_path: config_mount_path,
        read_only: Some(True),
      )

    let containers =
      list.map(template.containers, fn(c) {
        deployment.Container(
          ..c,
          volume_mounts: list.append(c.volume_mounts, [mount]),
        )
      })

    deployment.Deployment(
      ..dep,
      spec: deployment.DeploymentSpec(
        ..spec,
        template: deployment.PodTemplateSpec(
          ..template,
          containers: containers,
          volumes: list.append(template.volumes, [volume]),
        ),
      ),
    )
  })
}
