---
apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: Kustomization
metadata:
  name: vps-stage-1
  namespace: flux-system
spec:
  interval: "1m0s"
  path: "./infra/manifests/vps/_group-vps-stage-1"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: vps-base
