---
apiVersion: "kustomize.toolkit.fluxcd.io/v1"
kind: Kustomization
metadata:
  name: vps-base
  namespace: flux-system
spec:
  interval: "1m0s"
  path: "./manifests/vps/_group-vps-base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
